### ISSUE TITLE
interactables esp keybind

### ISSUE THREAD

**Issue by j-nihil** [Aquatic-Labs/Umbra-Mod-Menu#43]
when i set a keybind for the interactables esp, only the teleporter is shown until i activate the esp trough the menu, then the keybind works as intended.

**Comment by i-have-two-moms** [comment]
I think what usually works for me is to use the keybind to disable it before I go into the teleporter and activate it again with the keybind when the new map has loaded

**Comment by AquaticLabs** [comment]
Referencing #42 so it can pop up there (I personally suck at github NeonixRIT is the pro..)

**Comment by NeonixRIT** [comment]
Keybind system is changing in v3. This should be fixed in that release.
