### ISSUE TITLE
Cannot interact with menu after death

### ISSUE THREAD

**Issue by 7Noble** [Aquatic-Labs/Umbra-Mod-Menu#45]
Menu can be opened after death but cannot be navigated. I'm playing multiplayer and want to revive myself.
No idea how to fix this.
Tried changing different keyboard types and updating the menu.
Any solutions to this problem?

**Comment by NeonixRIT** [comment]
This is intended. From what I remember revive after death in solo isn't possible because the after run report comes up. Multiplayer as host might be possible if so, a revive button should be present. Currently this is not implemented. I will make sure to keep this in mind for version 3.0.

**Comment by NeonixRIT** [comment]
It is also hard to detect when a player is spectating. If I remember correctly the active unity "scene" changes and the variables used to change your Character's attributes are also destroyed (become Null/un-retrievable). These two things are the same thing the menu checks to tell of you're in game.
